- name: Install software development tools
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    - micro-bin
    - tig
    - git
    - highlight
    - visual-studio-code-bin
    - docker
    - docker-machine
    - docker-compose
    - nnn
  #  - kr
  become: yes
  become_user: "{{ installer_user }}"

- name: Install visual studio extensions
  include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ user }}"
        visual_studio_code_extensions:
          - ms-python.python
          - redhat.vscode-yaml
          - vscoss.vscode-ansible
          - tyriar.sort-lines
          - christian-kohler.path-intellisense
          - akamud.vscode-theme-onedark
          - mechatroner.rainbow-csv
        visual_studio_code_extensions_absent:
          - seanmcbreen.Spell
    become: true
    become_user: "{{ user }}"

- name: set default shell for users
  become: yes
  user:
    name: '{{ user }}'
    shell: /bin/zsh
- name: install oh-my-zsh

  become: yes
  become_user: "{{ user }}"



# TODO install oh-my-zsh
# install conda