      - name: Install fonts
        aur:
          name: "{{ item }}"
          skip_installed: true
        with_items:
          - ttf-ms-fonts
          - ttf-amiri
          - ttf-arabeyes-fonts
          - ttf-sil-lateef
          - ttf-sil-scheherazade
          - ttf-linux-libertine
          - ttf-inconsolata
          - ttf-unifont
          - siji-git
#           - ttf-emojione
        become: yes
        become_user: "{{ installer_user }}"
