- name: Install internet packages
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    - discord
    - android-messages-desktop
    # - yakyak
    - caprine
    - telegram-desktop
    - zoom
    - slack-desktop
    - qutebrowser
    - brave
    - google-chrome
    # - whatsie
    # Email, News, Podcasts, and RSS
    - neomutt
    - newsboat
    - haxor-news
    - skypeforlinux-stable-bin
    # - rainbowstream
    # Torrent
    # - transmission-cli
    # - transmission-cli-remote
    - tor
    - gitter
    - teamviewer
    - whatsapp-nativefier-dark
    - dropbox
    - signal-desktop
  become: yes
  become_user: "{{ installer_user }}"
  
