- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    # Media
    - youtube-dl
    - mpv
    - cmus
    - spotify
    - youtube-viewer
    - ncmpcpp
    - mpd
    # - cava
    # - cli-visualizer
  become: yes
  become_user: "{{ installer_user }}"
