- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    # Docs and PDF
    - zathura
    - pdftk
    - mupdf
  become: yes
  become_user: "{{ installer_user }}"
  
