
          # - advanced-ssh-config
          # - etcher
          # - hostsblock?
          # - https://github.com/alexanderjeurissen/ranger_devicons
          # - kshutdown
          # - libaacs
          # - libmpcdec
          # - onedrive
          # - python-httplib2 # for calcurse-caldav
          # - python-pywal
          # - safeeyes
          # - sc-im
          # - timeshift
          # - wavpack
