- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    - arandr
    - networkmanager-dmenu
    - offlineimap
    - blueman
    - rofi
    - rofi-scripts
    - rofi-calc
    - rofimoji
    - rofi-emoji
    - pulsemixer
    - python-i3-py
    - python-pretty-cron
    - notmuch
    - units
    - wine
    - zeal
    - pgcli
    - xclip
    - i3-layout-manager-git
    - i3ass
    - emoj
    - bcal
    - angband
    - curseofwar
    - rofi-surfraw-git
    - grv
    - ccat
    - watson
    - pdfgrep
    - howdoi
    - git-crypt
    - jp2a
    - nitrogen
    - xdotool
    - chafa
    - catimg
    - neofetch
#     - lyvi-git

    - feh
  become: yes
  become_user: "{{ installer_user }}"


          # - advanced-ssh-config
          # - etcher
          # - hostsblock?
          # - https://github.com/alexanderjeurissen/ranger_devicons
          # - kshutdown
          # - libaacs
          # - libmpcdec
          # - onedrive
          # - playerctl
          # - python-httplib2 # for calcurse-caldav
          # - python-pywal
          # - safeeyes
          # - sc-im
          # - timeshift
          # - wavpack
