- name: Recursively remove packages
  pacman:
    name: ['thunderbird', 'vlc', 'micro-manjaro', 'st-manjaro', 'hexchat', 'pidgin', 'palemoon-bin','manjaro-hello']
    state: absent
    extra_args: " --recursive"
  become: yes
