- name: Recursively remove packages
  pacman:
    name:
      - thunderbird
      - micro-manjaro
      - st-manjaro
      - hexchat
      - pidgin
      - palemoon-bin
      - manjaro-hello
    state: absent
    extra_args: "--recursive"
  become: yes

- name: remove manjaro dmenu
  pacman:
    name: "dmenu-manjaro"
    state: absent
    force: true
  become: yes
