- name: Recursively remove packages
  pacman:
    name: "{{ item }}"
    state: absent
    recurse: yes
  with_items:
    - thunderbird
    - vlc
    - micro-manjaro
    - st-manjaro
    - hexchat
    - pidgin
    - whatsapp-nativefier
    - palemoon-bin
    - manjaro-hello
  become: yes
