- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
    - sc-im
    - alacritty
    - alacritty-terminfo
    - kitty
    - kitty-terminfo
    # - mlterm
    - termite
    - termite-terminfo
    - hyper
    - curl
    - crazydiskinfo
    - rainbowstream
    - ack
    - parallel
    - tmux
    - speedtest-cli
    - jq
    - rclone
    - dialog
    - urlview
    - s3cmd
    - s4cmd
    - unzip
    - unrar
    - w3m
    - xcape
    - mediainfo
    - task-spooler
    - zsh
    - ncdu
    - calcurse
    - thefuck
    - tree
    - st-luke-git
    - espeak
    - translate-shell
    - rlwrap
    - mycli
    - gcalcli
    - net-tools
    - bitwarden-rofi-git
    - neovim
    - broot
    - stig
    - surfraw
    - ncpamixer
    - rofi-dmenu
    - dmenufm
    - unimatrix
    - pyradio-git
    - lsd
    - httpie
    - tldr
    - nvtop
    - cht.sh
    - glances
    - lazygit
    - slap
    - mps-youtube
    - navi
    - termshark-bin
    - slack-term
    - no-more-secrets
    - rtv
    - playerctl
    - spotify-dl-git
    - spotify-tui
    - nodejs-fx
    - cointop
    - patat-bin
    - fff
    - termgraph-git
    - lsix
    - fzf
    - go
    - python-mdv-git
    - ansiweather
    - khal
    - ddgr
    - s
    - googler
    # - mopidy-spotify
    # - saws
    - aws-cli
    - castero-git
    - hnwatch
    - termdown
    - ditaa
    - terminal-parrot
    - gtop
    - asciinema
    - python-mdv-git
    - fdupes
    - rmlint
    - wtfutil-bin
    - s-tui
    - autojump
    - thefuck
    - hub
    - python-soccer-cli-git
    - fd
    # - aerc
    
  become: yes
  become_user: "{{ installer_user }}"
