- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:          
    # - alacritty
    # - mlterm
    # - termite
    - hyper
    - curl
    - ack
    - parallel
    - tmux
    - speedtest-cli
    - jq
    - rclone
    - dialog
    - urlview
    - s3cmd
    - s4cmd
    - unzip
    - unrar
    - w3m
    - xcape
    - mediainfo
    - task-spooler
    - zsh
    - ncdu
    - calcurse
    - thefuck
    - tree
    - st-luke-git
    # - lastpass-cli
  become: yes
  become_user: "{{ installer_user }}"