- name: Install apps
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:          
    - alacritty
    - alacritty-terminfo
    - kitty
    - kitty-terminfo
    # - mlterm
    - termite
    - termite-terminfo
    - hyper
    - curl
    - crazydiskinfo
    - ack
    - parallel
    - tmux
    - speedtest-cli
    - jq
    - rclone
    - dialog
    - urlview
    - s3cmd
    - s4cmd
    - unzip
    - unrar
    - w3m
    - xcape
    - mediainfo
    - task-spooler
    - zsh
    - ncdu
    - calcurse
    - thefuck
    - tree
    - st-luke-git
    - espeak
    - translate-shell
    - rlwrap
    - mycli
    - gcalcli
    - net-tools
    - bitwarden-rofi-git
    - neovim
    - broot
    - stig
    - surfraw
    - ncpamixer
    - rofi-dmenu
    - dmenufm
    # - aerc
    
  become: yes
  become_user: "{{ installer_user }}"
